shiny:
  proxy:
    title: Office National des Forêts
    logo-url: file:///opt/shinyproxy/logo_onf.jpg
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    container-wait-time: 100000
    port: 8090
    authentication: simple
    admin-groups: admingroup
    # Example: 'simple' authentication configuration
    users:
    - name: po76844
      password: Password07
      groups: admingroup
    - name: user
      password: user
      groups: users
    # Example: 'ldap' authentication configuration
    ldap:
      #- url: ldap://ldap.forumsys.com:389/dc=example,dc=com
      #  user-dn-pattern: uid={0}
      #  group-search-base:
      #  group-search-filter: (uniqueMember={0})
      #  manager-dn: cn=read-only-admin,dc=example,dc=com
      #  manager-password: password
      - url: ldap://ldap.onf.fr:389/o=onf.fr
        user-dn-pattern: 
        group-search-base: 
        group-search-filter: 
        manager-dn: 
        manager-password: password
    # Docker configuration
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      internal-networking: true
  apps:
  - name: e-EMERGE
    display-name: e-EMERGE
    description: Aide à la caractérisation des tarifs et des mercuriales utilisés dans l'application PRODBOIS
    docker-cmd: ["R", "-e", "shiny::runApp('/root/spgftools')"]
    docker-image: pobsteta/shiny-gftools
    groups: [admingroup,users]
    docker-network: "host"
    
logging:
  file:
    shinyproxy.log
