proxy:
  title: Office National des Forêts
  logo-url: file:///opt/shinyproxy/logo_onf.jpg
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  container-wait-time: 100000
  port: 8090
  authentication: simple
  admin-groups: admingroup
  users:
  - name: po76844
    password: Password08
    groups: admingroup
  - name: user
    password: user
    groups: users    
  # Docker configuration
  docker:
    internal-networking: true
  specs:
  - id: e-EMERGE
    display-name: e-EMERGE
    description: Aide à la caractérisation des tarifs et des mercuriales utilisés dans l'application PRODBOIS
    container-cmd: ["R", "-e", "shiny::runApp('/root/spgftools')"]
    container-image: pobsteta/shiny-gftools
    access-groups: [admingroup,users]
    container-network: host
    
logging:
  file:
    shinyproxy.log
